name: solarian
on:
    push:
        branches: 
          - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup ninja and cmake
              run: sudo apt update -y && sudo apt install -y ninja-build cmake wget tar 
            - name: setup sdl
              run: |
                wget https://www.libsdl.org/release/SDL2-2.0.14.tar.gz
                tar -xvf SDL2-2.0.14.tar.gz
                mkdir sdl_build
                cd sdl_build
                cmake -G Ninja ../SDL2-2.0.14
                cmake --build .
                sudo cmake --install .
            - name: build
              run: |
                mkdir build
                cd build
                cmake -G Ninja ..
                cmake --install .
                ls
