name: CI
on:
    push:
        branches: 
          - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup ninja
              run: sudo apt update -y && sudo apt install -y ninja-build cmake
            - name: build
              run: |
                mkdir dz-01-1/build
                cd dz-01-1/build
                cmake -G Ninja ..
                cmake --build .
                cd ../..
                mkdir dz-01-2/build
                cd dz-01-2/build
                cmake -G Ninja ..
                cmake --build .
