name: solarian
on:
    push:
        branches: 
          - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup ninja
              run: sudo apt update -y && sudo apt install -y ninja-build cmake
            - name: build
              run: |
                mkdir build
                cd build
                cmake -G Ninja ..
                cmake --install .
                ls
